version: '3.6'

services:
    chroma:
      image: chromadb/chroma:latest
      volumes:
        - index_data:/chroma/.chroma/index
      ports:
        - 8000:8000
      networks:
        - net

volumes:
  index_data:

networks:
  net:
